apiVersion: v1
kind: Service
metadata:
  name: angular-app-service
spec:
  selector:
    app : angular-appliaction
  ports:
    - protocol: TCP
      port: 4200
      nodePort: 31234 
  type: NodePort